// Inline System Monitor for Canvas OS (no HTTP server needed)
// Usage: canvas.eval javaScript="<paste contents of this file>"
// Or load as: data:text/html,... (data URL)

(function(){
  var css='*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,Segoe\ UI,Roboto,sans-serif;background:#1a1a2e;color:#eee;padding:20px}.header{text-align:center;margin-bottom:25px}.header h1{font-size:22px;color:#4fc3f7;margin-bottom:5px}.header .time{color:#888;font-size:13px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:15px;margin-bottom:25px}.card{background:#16213e;border-radius:10px;padding:18px;text-align:center;border:1px solid #0f3460}.card .label{font-size:11px;color:#888;text-transform:uppercase;margin-bottom:6px}.card .value{font-size:28px;font-weight:bold}.card .status{font-size:11px;margin-top:6px}.status.good{color:#4caf50}.status.error{color:#f44336}.section{background:#16213e;border-radius:10px;padding:18px;margin-bottom:18px;border:1px solid #0f3460}.section h2{font-size:15px;color:#4fc3f7;margin-bottom:12px}.sys-info{display:grid;grid-template-columns:repeat(auto-fit,minmax(100px,1fr));gap:8px}.sys-item{background:#1a1a2e;padding:10px;border-radius:5px;text-align:center}.sys-item .label{font-size:10px;color:#888}.sys-item .value{font-size:14px;font-weight:bold}';

  var html='<style>'+css+'</style><div class=header><h1>🚀 OpenClaw System Monitor</h1><div class=time id=time>...</div></div><div class=grid><div class=card><div class=label>Gateway</div><div class=value id=gate>●</div><div class="status good" id=gateTxt>Online</div></div><div class=card><div class=label>Jobs</div><div class=value id=cron>-</div><div class=status id=cronTxt>-</div></div><div class=card><div class=label>Git</div><div class=value id=git>-</div><div class="status good">Commits</div></div><div class=card><div class=label>Uptime</div><div class=value id=up>-</div><div class=status>-</div></div></div><div class=section><h2>📊 System</h2><div class=sys-info><div class=sys-item><div class=label>Model</div><div class=value id=model>-</div></div><div class=sys-item><div class=label>Channel</div><div class=value id=channel>-</div></div><div class=sys-item><div class=label>Status</div><div class=value id=status>-</div></div></div></div>';

  var js='var t=function(){document.getElementById("time").innerText=new Date().toLocaleString("en-IN",{timeZone:"Asia/Kolkata"})};t();setInterval(t,1000);window.app={setValue:function(k,v){var e=document.getElementById(k);if(e)e.innerText=v},loadData:function(d){if(!d)return;if(d.gateway!==undefined){document.getElementById("gate").innerText=d.gateway?"●":"○";document.getElementById("gateTxt").innerText=d.gateway?"Online":"Offline";document.getElementById("gateTxt").className="status "+(d.gateway?"good":"error")}if(d.cronCount!==undefined)document.getElementById("cron").innerText=d.cronCount;if(d.uptime!==undefined)document.getElementById("up").innerText=d.uptime;if(d.gitCommits!==undefined)document.getElementById("git").innerText=d.gitCommits;if(d.model)document.getElementById("model").innerText=d.model;if(d.channel)document.getElementById("channel").innerText=d.channel;if(d.status)document.getElementById("status").innerText=d.status},notify:function(m){console.log("Monitor:",m)}};window.app.notify("Inline mode ready");';

  // Inject into page
  document.body.innerHTML=html;
  var s=document.createElement("script");s.textContent=js;document.body.appendChild(s);
  console.log("OpenClaw System Monitor injected");
})();